## This is basic continuous integration build for your Quarkus application.

name: SQL Runner Native Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Test
        run: ./gradlew test

      - name: Build
        run: ./gradlew build -x test --info --scan -Dquarkus.package.type=native -Dquarkus.native.container-build=true
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: build-reports
          path: build/reports/
