## This is basic continuous integration build for your Quarkus application.

name: Quarkus Codestart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build --info --scan -Dquarkus.package.type=native -Dquarkus.native.container-build=true
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: build-reports
          path: build/reports/
